---
title: "Descriptive"
author: "Mingxu Shan"
date: "3/10/2019"
output: github_document
---
```{r}
library(tidyverse)
library(readxl)
```

```{r}
olddata <- read_excel("data/Master worksheet CTICU extubation times .xls", 
    sheet = "Master data", col_types = c("numeric", 
        "numeric", "text", "date", "date", 
        "date", "date", "text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "numeric", 
        "numeric", "numeric", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "numeric", "text", "numeric", "text", 
        "numeric", "numeric", "text", "text", 
        "text", "text", "date", "date", 
        "date", "date", "date", 
        "text", "numeric", "text", "numeric", 
        "numeric", "text", "numeric", "text", 
        "text", "numeric", "numeric", "text", 
        "text", "text", "text", "text", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric"))
```


```{r new dataset}

rawdata <-  read_excel("data/new master data file 3 14 2019.xlsx", 
    col_types = c("text", "text", "date", 
        "date", "date", "numeric", "text", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "numeric", "numeric", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "numeric", "text", 
        "numeric", "text", "numeric", "numeric", 
        "text", "text", "text", "text", "text", 
        "numeric", "text", "numeric", "date", 
        "date", "date", "date", 
        "date", "text", "numeric", "text", 
        "numeric", "numeric", "text", "numeric", 
        "text", "text", "numeric", "numeric", 
        "text", "text", "text", "text", "text", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric"))


```


```{r descriptive data}
desdata <- rawdata %>% 
  separate("Surgery duration", into = c("Sdate", "Stime"), sep= " ") %>%
  separate("OR Exit Date And Time", into = c("OREdate", "OREtime"), sep= " ") %>%
  separate("OREtime", into = c("OREhour", "OREmin","OREsec"), sep= ":") %>%
  separate("Stime", into = c("Shour","Smin","Ssec"), sep= ":") %>% 
  mutate (Shour=as.numeric(Shour), Smin=as.numeric(Smin), Stime = Shour+ (Smin/60),
          OREhour = as.numeric(OREhour) ,
          period = ifelse (OREhour <18 & OREhour >=7,  "P1", "P2"),
          Ethnicity = NA,
          Reintub = coalesce(`Re-intubated During Hospital Stay`, `Postop Intubation/Reintubation During Hospital Stay`),
          Mor_disc = coalesce(`Mort-DC Status`,`Discharge / Mortality Status`)
          
          ) %>%

  rename(age = "Patient Age", 
         sex = "Sex", 
         BMI = "BMI", 
         PMM = "Predicted Morbidity or Mortality", 
         PRM = "Predicted Risk of Mortality", 
         PPV = "Predicted Prolonged Ventilation", 
         Reop = "Incidence",
         Urgent = "Status",
         Sug_Dur = "Stime",
         Pri_MI = "Prior MI",
         HF_w2w = "Heart Failure within 2 weeks",
         NYHA = "Classification-NYHA",
         smoker = "RF-Tobacco Use",
         lung = "RF-Chronic Lung Disease",
         PFT = "RF-Pulmonary Function Test",
         FEV = "RF-Forced Expiratory Volume Predicted",
         DLCOT = "DLCO Test Performed",
         DLCO = "DLCO Predicted",
         RFD = "RF-Renal Fail-Dialysis",
         PAD = "RF-Peripheral Arterial Disease",
         #Main outcome
         IHV = "Initial Hours Ventilated",
         #Secondary outcome
         Post_pneu = "Post-Op-Pulm-Pneumonia", 
         Post_throm = "Post-Op-Venous Thromboembolism-VTE",
         Post_stroke = "Post-Op-Neuro-Stroke Perm"  ,
         Re_ICU = "Readmission to ICU" ,
         Hos_LOS = "LOS-Admit-Discharge" , 
         ICU_LOS = "Total Hrs ICU",
         #Post-operative blood product transfusion 
         POBPT = "Blood Prod" ,                                        
         #Total blood transfusion units
         TBU = "Total units (all blood products)",      
         XCT = "Cross Clamp Time (min)",                             
         CPBT = "Cardiopulmonary Bypass Time"                        
         ) %>% 
  select(age,
       sex,
       Ethnicity,
       BMI, 
       PMM , 
       PRM , 
       PPV,
       Reop ,
       Urgent ,
       Sug_Dur ,
       Pri_MI ,
       HF_w2w ,
       NYHA ,
       smoker,
       lung,
       PFT,
       FEV,
       DLCOT ,
       DLCO,
       RFD ,
       PAD,
       OREhour,
       IHV,
       period,
       # secondary outcome
       Reintub, 
       Post_pneu, 
       Post_throm ,
       Post_stroke ,
       Re_ICU , 
       Hos_LOS, 
       ICU_LOS, 
       Mor_disc,
       # new variables added by new dataset 
       POBPT,
       TBU,
       XCT,
       CPBT
       ) %>% 
  mutate(IHV_24 = IHV)

        


# combine ethnicity

desdata$Ethnicity[rawdata$`Race - White` == "Yes"] = "White"
desdata$Ethnicity[rawdata$`Race - Black / African American` == "Yes"] = "Black"
desdata$Ethnicity[rawdata$`Race - Asian` == "Yes"] = "Asian"
desdata$Ethnicity[rawdata$`Race - American Indian / Alaskan Native` == "Yes"] = "American Indian"
desdata$Ethnicity[rawdata$`Race - Native Hawaiian / Pacific Islander` == "Yes"] = "Hawaiian"
desdata$Ethnicity[rawdata$`Race - Other` == "Yes"] = "Other"
desdata$Ethnicity[rawdata$`Race Documented` == "No"] = "No document"
```


```{r}
desdata <- desdata %>% mutate( IHV_24 = IHV)
desdata$IHV_24[desdata$IHV>24] = NA 

glmdata <- desdata
```


```{r}
names(rawdata)
names(olddata)
names(desdata)
```
#Categorical 

```{r sex descriptive}
#desdata$sex[desdata$sex == "Not documented"] <- NA
length(desdata$sex)
sum(is.na(desdata$sex))
sum(is.na(desdata$sex)) / length(desdata$sex)
table(desdata$sex)

#table(desdata$sex) / length(desdata$sex)
paste(round(100*(table(desdata$sex) / 861), 2), "%", sep="")

length(desdata$sex[desdata$period == "P1"])
length(desdata$sex[desdata$period == "P2"])

sum(is.na(desdata$sex[desdata$period == "P1"]))
sum(is.na(desdata$sex[desdata$period == "P2"]))

table(desdata$sex[desdata$period == "P1"]) 
table(desdata$sex[desdata$period == "P2"]) 

#table(desdata$sex[desdata$period == "P1"]) / length(desdata$sex[desdata$period == "P1"])
paste(round(100*(table(desdata$sex[desdata$period == "P1"]) / length(desdata$sex[desdata$period == "P1"])), 2), "%", sep="")

#table(desdata$sex[desdata$period == "P2"]) / length(desdata$sex[desdata$period == "P2"])
paste(round(100*(table(desdata$sex[desdata$period == "P2"]) / length(desdata$sex[desdata$period == "P2"])), 2), "%", sep="")
chisq.test(desdata$sex,desdata$period, correct = FALSE)

```

```{r Ethnicity descriptive}
glmdata$Ethnicity[glmdata$Ethnicity == "No document"] <- NA
glmdata$Ethnicity <- as.factor(glmdata$Ethnicity) %>%
  relevel(glmdata$Ethnicity, ref="White")

length(glmdata$Ethnicity)
sum(is.na(glmdata$Ethnicity))
sum(is.na(glmdata$Ethnicity)) / length(glmdata$Ethnicity)
table(glmdata$Ethnicity)

#table(glmdata$Ethnicity) / length(glmdata$Ethnicity)
paste(round(100*(table(glmdata$Ethnicity) / 861), 2), "%", sep="")

length(glmdata$Ethnicity[glmdata$period == "P1"])
length(glmdata$Ethnicity[glmdata$period == "P2"])

sum(is.na(glmdata$Ethnicity[glmdata$period == "P1"]))
sum(is.na(glmdata$Ethnicity[glmdata$period == "P2"]))

table(glmdata$Ethnicity[glmdata$period == "P1"]) 
table(glmdata$Ethnicity[glmdata$period == "P2"]) 

#table(glmdata$Ethnicity[glmdata$period == "P1"]) / length(glmdata$Ethnicity[glmdata$period == "P1"])
paste(round(100*(table(glmdata$Ethnicity[glmdata$period == "P1"]) / length(glmdata$Ethnicity[glmdata$period == "P1"])), 2), "%", sep="")

#table(glmdata$Ethnicity[glmdata$period == "P2"]) / length(glmdata$Ethnicity[glmdata$period == "P2"])
paste(round(100*(table(glmdata$Ethnicity[glmdata$period == "P2"]) / length(glmdata$Ethnicity[glmdata$period == "P2"])), 2), "%", sep="")


chisq.test(glmdata$Ethnicity,glmdata$period, correct = FALSE)
```

```{r Reop descriptive}
glmdata <- glmdata %>% 
  mutate(Reop = ifelse(Reop == "First cardiovascular surgery", "Yes", "No"))

length(glmdata$Reop)
sum(is.na(glmdata$Reop))
sum(is.na(glmdata$Reop)) / length(glmdata$Reop)
table(glmdata$Reop)

#table(glmdata$Reop) / length(glmdata$Reop)
paste(round(100*(table(glmdata$Reop) / (length(na.omit(glmdata$Reop)))), 2), "%", sep="")

length(na.omit(glmdata$Reop[glmdata$period == "P1"]))
length(na.omit(glmdata$Reop[glmdata$period == "P2"]))

sum(is.na(glmdata$Reop[glmdata$period == "P1"]))
sum(is.na(glmdata$Reop[glmdata$period == "P2"]))

table(glmdata$Reop[glmdata$period == "P1"]) 
table(glmdata$Reop[glmdata$period == "P2"]) 

#table(glmdata$Reop[glmdata$period == "P1"]) / length(glmdata$Reop[glmdata$period == "P1"])
paste(round(100*(table(glmdata$Reop[glmdata$period == "P1"]) / length(na.omit(glmdata$Reop[glmdata$period == "P1"]))), 2), "%", sep="")

#table(glmdata$Reop[glmdata$period == "P2"]) / length(glmdata$Reop[glmdata$period == "P2"])
paste(round(100*(table(glmdata$Reop[glmdata$period == "P2"]) / length(na.omit(glmdata$Reop[glmdata$period == "P2"]))), 2), "%", sep="")



fisher.test(glmdata$Reop,glmdata$period)
```

```{r Urgent descriptive}
#desdata$Urgent[desdata$Urgent == "Not documented"] <- NA
length(desdata$Urgent)
sum(is.na(desdata$Urgent))
sum(is.na(desdata$Urgent)) / length(desdata$Urgent)
table(desdata$Urgent)

#table(desdata$Urgent) / length(desdata$Urgent)
paste(round(100*(table(desdata$Urgent) / 861), 2), "%", sep="")

length(desdata$Urgent[desdata$period == "P1"])
length(desdata$Urgent[desdata$period == "P2"])

sum(is.na(desdata$Urgent[desdata$period == "P1"]))
sum(is.na(desdata$Urgent[desdata$period == "P2"]))

table(desdata$Urgent[desdata$period == "P1"]) 
table(desdata$Urgent[desdata$period == "P2"]) 

#table(desdata$Urgent[desdata$period == "P1"]) / length(desdata$Urgent[desdata$period == "P1"])
paste(round(100*(table(desdata$Urgent[desdata$period == "P1"]) / length(desdata$Urgent[desdata$period == "P1"])), 2), "%", sep="")

#table(desdata$Urgent[desdata$period == "P2"]) / length(desdata$Urgent[desdata$period == "P2"])
paste(round(100*(table(desdata$Urgent[desdata$period == "P2"]) / length(desdata$Urgent[desdata$period == "P2"])), 2), "%", sep="")


chisq.test(desdata$Urgent,desdata$period, correct = FALSE)
```


```{r Pri_MI descriptive}
glmdata$Pri_MI[glmdata$Pri_MI == "Unknown"] <- NA
length(glmdata$Pri_MI)
sum(is.na(glmdata$Pri_MI))
sum(is.na(glmdata$Pri_MI)) / length(glmdata$Pri_MI)
table(glmdata$Pri_MI)

#table(glmdata$Pri_MI) / length(glmdata$Pri_MI)
paste(round(100*(table(glmdata$Pri_MI) / (length(na.omit(glmdata$Pri_MI)))), 2), "%", sep="")

length(na.omit(glmdata$Pri_MI[glmdata$period == "P1"]))
length(na.omit(glmdata$Pri_MI[glmdata$period == "P2"]))

sum(is.na(glmdata$Pri_MI[glmdata$period == "P1"]))
sum(is.na(glmdata$Pri_MI[glmdata$period == "P2"]))

table(glmdata$Pri_MI[glmdata$period == "P1"]) 
table(glmdata$Pri_MI[glmdata$period == "P2"]) 

#table(glmdata$Pri_MI[glmdata$period == "P1"]) / length(glmdata$Pri_MI[glmdata$period == "P1"])
paste(round(100*(table(glmdata$Pri_MI[glmdata$period == "P1"]) / length(na.omit(glmdata$Pri_MI[glmdata$period == "P1"]))), 2), "%", sep="")

#table(glmdata$Pri_MI[glmdata$period == "P2"]) / length(glmdata$Pri_MI[glmdata$period == "P2"])
paste(round(100*(table(glmdata$Pri_MI[glmdata$period == "P2"]) / length(na.omit(glmdata$Pri_MI[glmdata$period == "P2"]))), 2), "%", sep="")

chisq.test(glmdata$Pri_MI,glmdata$period, correct = FALSE)
```


```{r HF_w2w descriptive}
glmdata$HF_w2w[desdata$HF_w2w == "Unknown"] <- NA
length(desdata$HF_w2w)
sum(is.na(desdata$HF_w2w))
sum(is.na(desdata$HF_w2w)) / length(desdata$HF_w2w)
table(desdata$HF_w2w)

#table(desdata$HF_w2w) / length(desdata$HF_w2w)
paste(round(100*(table(desdata$HF_w2w) / 861), 2), "%", sep="")

length(desdata$HF_w2w[desdata$period == "P1"])
length(desdata$HF_w2w[desdata$period == "P2"])

sum(is.na(desdata$HF_w2w[desdata$period == "P1"]))
sum(is.na(desdata$HF_w2w[desdata$period == "P2"]))

table(desdata$HF_w2w[desdata$period == "P1"]) 
table(desdata$HF_w2w[desdata$period == "P2"]) 

#table(desdata$HF_w2w[desdata$period == "P1"]) / length(desdata$HF_w2w[desdata$period == "P1"])
paste(round(100*(table(desdata$HF_w2w[desdata$period == "P1"]) / length(desdata$HF_w2w[desdata$period == "P1"])), 2), "%", sep="")

#table(desdata$HF_w2w[desdata$period == "P2"]) / length(desdata$HF_w2w[desdata$period == "P2"])
paste(round(100*(table(desdata$HF_w2w[desdata$period == "P2"]) / length(desdata$HF_w2w[desdata$period == "P2"])), 2), "%", sep="")
chisq.test(desdata$HF_w2w,desdata$period, correct = FALSE)
```

```{r NYHA descriptive}
#desdata$NYHA[desdata$NYHA == "Not documented"] <- NA
length(desdata$NYHA)
sum(is.na(desdata$NYHA))
sum(is.na(desdata$NYHA)) / length(desdata$NYHA)
table(desdata$NYHA)

#table(desdata$NYHA) / length(desdata$NYHA)
paste(round(100*(table(desdata$NYHA) / 861), 2), "%", sep="")

length(desdata$NYHA[desdata$period == "P1"])
length(desdata$NYHA[desdata$period == "P2"])

sum(is.na(desdata$NYHA[desdata$period == "P1"]))
sum(is.na(desdata$NYHA[desdata$period == "P2"]))

table(desdata$NYHA[desdata$period == "P1"]) 
table(desdata$NYHA[desdata$period == "P2"]) 

#table(desdata$NYHA[desdata$period == "P1"]) / length(desdata$NYHA[desdata$period == "P1"])
paste(round(100*(table(desdata$NYHA[desdata$period == "P1"]) / length(desdata$NYHA[desdata$period == "P1"])), 2), "%", sep="")

#table(desdata$NYHA[desdata$period == "P2"]) / length(desdata$NYHA[desdata$period == "P2"])
paste(round(100*(table(desdata$NYHA[desdata$period == "P2"]) / length(desdata$NYHA[desdata$period == "P2"])), 2), "%", sep="")

```

```{r smoker descriptive}
glmdata$smoker <- "Yes"
glmdata$smoker[desdata$smoker == "Smoking status unknown"] <- NA
glmdata$smoker[desdata$smoker == "Never smoker"] <- "No"
length(glmdata$smoker)
sum(is.na(glmdata$smoker))
sum(is.na(glmdata$smoker)) / length(glmdata$smoker)
table(glmdata$smoker)

#table(glmdata$smoker) / length(glmdata$smoker)
paste(round(100*(table(glmdata$smoker) / (length(na.omit(glmdata$smoker)))), 2), "%", sep="")

length(na.omit(glmdata$smoker[glmdata$period == "P1"]))
length(na.omit(glmdata$smoker[glmdata$period == "P2"]))

sum(is.na(glmdata$smoker[glmdata$period == "P1"]))
sum(is.na(glmdata$smoker[glmdata$period == "P2"]))

table(glmdata$smoker[glmdata$period == "P1"]) 
table(glmdata$smoker[glmdata$period == "P2"]) 

#table(glmdata$smoker[glmdata$period == "P1"]) / length(glmdata$smoker[glmdata$period == "P1"])
paste(round(100*(table(glmdata$smoker[glmdata$period == "P1"]) / length(na.omit(glmdata$smoker[glmdata$period == "P1"]))), 2), "%", sep="")

#table(glmdata$smoker[glmdata$period == "P2"]) / length(glmdata$smoker[glmdata$period == "P2"])
paste(round(100*(table(glmdata$smoker[glmdata$period == "P2"]) / length(na.omit(glmdata$smoker[glmdata$period == "P2"]))), 2), "%", sep="")

chisq.test(glmdata$smoker,glmdata$period, correct = FALSE)
```

```{r lung descriptive}

glmdata$lung <- "Yes"
glmdata$lung[desdata$lung == "No"] <- "No"
glmdata$lung[desdata$lung == "Unknown"] <- NA

length(glmdata$lung)
sum(is.na(glmdata$lung))
sum(is.na(glmdata$lung)) / length(glmdata$lung)
table(glmdata$lung)

#table(glmdata$lung) / length(glmdata$lung)
paste(round(100*(table(glmdata$lung) / 861), 2), "%", sep="")

length(glmdata$lung[glmdata$period == "P1"])
length(glmdata$lung[glmdata$period == "P2"])

sum(is.na(glmdata$lung[glmdata$period == "P1"]))
sum(is.na(glmdata$lung[glmdata$period == "P2"]))

table(glmdata$lung[glmdata$period == "P1"]) 
table(glmdata$lung[glmdata$period == "P2"]) 

#table(glmdata$lung[glmdata$period == "P1"]) / length(glmdata$lung[glmdata$period == "P1"])
paste(round(100*(table(glmdata$lung[glmdata$period == "P1"]) / length(glmdata$lung[glmdata$period == "P1"])), 2), "%", sep="")

#table(glmdata$lung[glmdata$period == "P2"]) / length(glmdata$lung[glmdata$period == "P2"])
paste(round(100*(table(glmdata$lung[glmdata$period == "P2"]) / length(glmdata$lung[glmdata$period == "P2"])), 2), "%", sep="")

chisq.test(glmdata$lung,glmdata$period, correct = FALSE)
```

```{r PFT descriptive}


glmdata$PFT[desdata$PFT == "Unknown"] <- NA

length(glmdata$PFT)
sum(is.na(glmdata$PFT))
sum(is.na(glmdata$PFT)) / length(glmdata$PFT)
table(glmdata$PFT)

#table(glmdata$PFT) / length(glmdata$PFT)
paste(round(100*(table(glmdata$PFT) / 861), 2), "%", sep="")

length(glmdata$PFT[glmdata$period == "P1"])
length(glmdata$PFT[glmdata$period == "P2"])

sum(is.na(glmdata$PFT[glmdata$period == "P1"]))
sum(is.na(glmdata$PFT[glmdata$period == "P2"]))

table(glmdata$PFT[glmdata$period == "P1"]) 
table(glmdata$PFT[glmdata$period == "P2"]) 

#table(glmdata$PFT[glmdata$period == "P1"]) / length(glmdata$PFT[glmdata$period == "P1"])
paste(round(100*(table(glmdata$PFT[glmdata$period == "P1"]) / length(glmdata$PFT[glmdata$period == "P1"])), 2), "%", sep="")

#table(glmdata$PFT[glmdata$period == "P2"]) / length(glmdata$PFT[glmdata$period == "P2"])
paste(round(100*(table(glmdata$PFT[glmdata$period == "P2"]) / length(glmdata$PFT[glmdata$period == "P2"])), 2), "%", sep="")

chisq.test(glmdata$PFT,glmdata$period, correct = FALSE)
```

```{r DLCOT descriptive}
#desdata$DLCOT[desdata$DLCOT == "Not documented"] <- NA
length(desdata$DLCOT)
sum(is.na(desdata$DLCOT))
sum(is.na(desdata$DLCOT)) / length(desdata$DLCOT)
table(desdata$DLCOT)

#table(desdata$DLCOT) / length(desdata$DLCOT)
paste(round(100*(table(desdata$DLCOT) / 861), 2), "%", sep="")

length(desdata$DLCOT[desdata$period == "P1"])
length(desdata$DLCOT[desdata$period == "P2"])

sum(is.na(desdata$DLCOT[desdata$period == "P1"]))
sum(is.na(desdata$DLCOT[desdata$period == "P2"]))

table(desdata$DLCOT[desdata$period == "P1"]) 
table(desdata$DLCOT[desdata$period == "P2"]) 

#table(desdata$DLCOT[desdata$period == "P1"]) / length(desdata$DLCOT[desdata$period == "P1"])
paste(round(100*(table(desdata$DLCOT[desdata$period == "P1"]) / length(desdata$DLCOT[desdata$period == "P1"])), 2), "%", sep="")

#table(desdata$DLCOT[desdata$period == "P2"]) / length(desdata$DLCOT[desdata$period == "P2"])
paste(round(100*(table(desdata$DLCOT[desdata$period == "P2"]) / length(desdata$DLCOT[desdata$period == "P2"])), 2), "%", sep="")
```

```{r RFD descriptive}


glmdata$RFD[desdata$RFD == "Unknown"] <- NA

length(glmdata$RFD)
sum(is.na(glmdata$RFD))
sum(is.na(glmdata$RFD)) / length(glmdata$RFD)
table(glmdata$RFD)

#table(glmdata$RFD) / length(glmdata$RFD)
paste(round(100*(table(glmdata$RFD) / 861), 2), "%", sep="")

length(glmdata$RFD[glmdata$period == "P1"])
length(glmdata$RFD[glmdata$period == "P2"])

sum(is.na(glmdata$RFD[glmdata$period == "P1"]))
sum(is.na(glmdata$RFD[glmdata$period == "P2"]))

table(glmdata$RFD[glmdata$period == "P1"]) 
table(glmdata$RFD[glmdata$period == "P2"]) 

#table(glmdata$RFD[glmdata$period == "P1"]) / length(glmdata$RFD[glmdata$period == "P1"])
paste(round(100*(table(glmdata$RFD[glmdata$period == "P1"]) / length(glmdata$RFD[glmdata$period == "P1"])), 2), "%", sep="")

#table(glmdata$RFD[glmdata$period == "P2"]) / length(glmdata$RFD[glmdata$period == "P2"])
paste(round(100*(table(glmdata$RFD[glmdata$period == "P2"]) / length(glmdata$RFD[glmdata$period == "P2"])), 2), "%", sep="")

chisq.test(glmdata$RFD,glmdata$period, correct = FALSE)
```

```{r PAD descriptive}
#desdata$PAD[desdata$PAD == "Not documented"] <- NA
length(desdata$PAD)
sum(is.na(desdata$PAD))
sum(is.na(desdata$PAD)) / length(desdata$PAD)
table(desdata$PAD)

#table(desdata$PAD) / length(desdata$PAD)
paste(round(100*(table(desdata$PAD) / 861), 2), "%", sep="")

length(desdata$PAD[desdata$period == "P1"])
length(desdata$PAD[desdata$period == "P2"])

sum(is.na(desdata$PAD[desdata$period == "P1"]))
sum(is.na(desdata$PAD[desdata$period == "P2"]))

table(desdata$PAD[desdata$period == "P1"]) 
table(desdata$PAD[desdata$period == "P2"]) 

#table(desdata$PAD[desdata$period == "P1"]) / length(desdata$PAD[desdata$period == "P1"])
paste(round(100*(table(desdata$PAD[desdata$period == "P1"]) / length(desdata$PAD[desdata$period == "P1"])), 2), "%", sep="")

#table(desdata$PAD[desdata$period == "P2"]) / length(desdata$PAD[desdata$period == "P2"])
paste(round(100*(table(desdata$PAD[desdata$period == "P2"]) / length(desdata$PAD[desdata$period == "P2"])), 2), "%", sep="")

chisq.test(glmdata$PAD,glmdata$period, correct = FALSE)
```

```{r POBPT  descriptive}




length(glmdata$POBPT )
sum(is.na(glmdata$POBPT ))
sum(is.na(glmdata$POBPT )) / length(glmdata$POBPT )
table(glmdata$POBPT )

#table(glmdata$POBPT ) / length(glmdata$POBPT )
paste(round(100*(table(glmdata$POBPT ) / (length(na.omit(glmdata$POBPT )))), 2), "%", sep="")

length(na.omit(glmdata$POBPT [glmdata$period == "P1"]))
length(na.omit(glmdata$POBPT [glmdata$period == "P2"]))

sum(is.na(glmdata$POBPT [glmdata$period == "P1"]))
sum(is.na(glmdata$POBPT [glmdata$period == "P2"]))

table(glmdata$POBPT [glmdata$period == "P1"]) 
table(glmdata$POBPT [glmdata$period == "P2"]) 

#table(glmdata$POBPT [glmdata$period == "P1"]) / length(glmdata$POBPT [glmdata$period == "P1"])
paste(round(100*(table(glmdata$POBPT [glmdata$period == "P1"]) / length(na.omit(glmdata$POBPT [glmdata$period == "P1"]))), 2), "%", sep="")

#table(glmdata$POBPT [glmdata$period == "P2"]) / length(glmdata$POBPT [glmdata$period == "P2"])
paste(round(100*(table(glmdata$POBPT [glmdata$period == "P2"]) / length(na.omit(glmdata$POBPT [glmdata$period == "P2"]))), 2), "%", sep="")

chisq.test(glmdata$POBPT ,glmdata$period, correct = FALSE)

```


#Continuous
```{r age descriptive}
desdata$age[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$age[desdata$period == "P1"])
desdata$age[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$age[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$age[desdata$period == "P2"])
desdata$age[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$age %>% na.omit() %>% length()
summary(desdata$age)
desdata$age %>% na.omit() %>% sd()
```
```{r age t}
var.test(desdata$age[desdata$period == "P2"], desdata$age[desdata$period == "P1"])
t.test(x= desdata$age[desdata$period == "P1"], y = desdata$age[desdata$period == "P2"], paired = FALSE, var.equal = TRUE, conf.level = 0.95)
```

```{r PMM descriptive}
desdata$PMM[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$PMM[desdata$period == "P1"])
desdata$PMM[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$PMM[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$PMM[desdata$period == "P2"])
desdata$PMM[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$PMM %>% na.omit() %>% length()
summary(desdata$PMM)
desdata$PMM %>% na.omit() %>% sd()
```

```{r PMM t}
var.test(desdata$PMM[desdata$period == "P2"], desdata$PMM[desdata$period == "P1"])
t.test(x= desdata$PMM[desdata$period == "P1"], y = desdata$PMM[desdata$period == "P2"], paired = FALSE, var.equal = FALSE, conf.level = 0.95)
```

```{r PRM descriptive}
desdata$PRM[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$PRM[desdata$period == "P1"])
desdata$PRM[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$PRM[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$PRM[desdata$period == "P2"])
desdata$PRM[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$PRM %>% na.omit() %>% length()
summary(desdata$PRM)
desdata$PRM %>% na.omit() %>% sd()
```

```{r PRM t}
var.test(desdata$PRM[desdata$period == "P2"], desdata$PRM[desdata$period == "P1"])
t.test(x= desdata$PRM[desdata$period == "P1"], y = desdata$PRM[desdata$period == "P2"], paired = FALSE, var.equal = TRUE, conf.level = 0.95)
```

```{r PPV descriptive}
desdata$PPV[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$PPV[desdata$period == "P1"])
desdata$PPV[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$PPV[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$PPV[desdata$period == "P2"])
desdata$PPV[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$PPV %>% na.omit() %>% length()
summary(desdata$PPV)
desdata$PPV %>% na.omit() %>% sd()
```

```{r PPV t}
var.test(desdata$PPV[desdata$period == "P2"], desdata$PPV[desdata$period == "P1"])
t.test(x= desdata$PPV[desdata$period == "P1"], y = desdata$PPV[desdata$period == "P2"], paired = FALSE, var.equal = TRUE, conf.level = 0.95)
```

```{r Sug_Dur descriptive}
desdata$Sug_Dur[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$Sug_Dur[desdata$period == "P1"])
desdata$Sug_Dur[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$Sug_Dur[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$Sug_Dur[desdata$period == "P2"])
desdata$Sug_Dur[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$Sug_Dur %>% na.omit() %>% length()
summary(desdata$Sug_Dur)
desdata$Sug_Dur %>% na.omit() %>% sd()
```

```{r Sug_Dur t}
var.test(desdata$Sug_Dur[desdata$period == "P2"], desdata$Sug_Dur[desdata$period == "P1"])
t.test(x= desdata$Sug_Dur[desdata$period == "P1"], y = desdata$Sug_Dur[desdata$period == "P2"], paired = FALSE, var.equal = FALSE, conf.level = 0.95)
```

```{r FEV descriptive}
desdata$FEV[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$FEV[desdata$period == "P1"])
desdata$FEV[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$FEV[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$FEV[desdata$period == "P2"])
desdata$FEV[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$FEV %>% na.omit() %>% length()
summary(desdata$FEV)
desdata$FEV %>% na.omit() %>% sd()
```

```{r FEV t}
var.test(desdata$FEV[desdata$period == "P2"], desdata$FEV[desdata$period == "P1"])
t.test(x= desdata$FEV[desdata$period == "P1"], y = desdata$FEV[desdata$period == "P2"], paired = FALSE, var.equal = TRUE, conf.level = 0.95)
```

```{r DLCO descriptive}
desdata$DLCO[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$DLCO[desdata$period == "P1"])
desdata$DLCO[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$DLCO[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$DLCO[desdata$period == "P2"])
desdata$DLCO[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$DLCO %>% na.omit() %>% length()
summary(desdata$DLCO)
desdata$DLCO %>% na.omit() %>% sd()
```

```{r DLCO t}
var.test(desdata$DLCO[desdata$period == "P2"], desdata$DLCO[desdata$period == "P1"])
t.test(x= desdata$DLCO[desdata$period == "P1"], y = desdata$DLCO[desdata$period == "P2"], paired = FALSE, var.equal = TRUE, conf.level = 0.95)
```

```{r TBU descriptive}
desdata$TBU[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$TBU[desdata$period == "P1"])
desdata$TBU[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$TBU[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$TBU[desdata$period == "P2"])
desdata$TBU[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$TBU %>% na.omit() %>% length()
summary(desdata$TBU)
desdata$TBU %>% na.omit() %>% sd()
```

```{r TBU t}
var.test(desdata$TBU[desdata$period == "P2"], desdata$TBU[desdata$period == "P1"])
t.test(x= desdata$TBU[desdata$period == "P1"], y = desdata$TBU[desdata$period == "P2"], paired = FALSE, var.equal = TRUE, conf.level = 0.95)
```

```{r XCT descriptive}
desdata$XCT[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$XCT[desdata$period == "P1"])
desdata$XCT[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$XCT[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$XCT[desdata$period == "P2"])
desdata$XCT[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$XCT %>% na.omit() %>% length()
summary(desdata$XCT)
desdata$XCT %>% na.omit() %>% sd()
```

```{r XCT t}
var.test(desdata$XCT[desdata$period == "P2"], desdata$XCT[desdata$period == "P1"])
t.test(x= desdata$XCT[desdata$period == "P1"], y = desdata$XCT[desdata$period == "P2"], paired = FALSE, var.equal = TRUE, conf.level = 0.95)
```

```{r CPBT descriptive}
desdata$CPBT[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$CPBT[desdata$period == "P1"])
desdata$CPBT[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$CPBT[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$CPBT[desdata$period == "P2"])
desdata$CPBT[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$CPBT %>% na.omit() %>% length()
summary(desdata$CPBT)
desdata$CPBT %>% na.omit() %>% sd()
```

```{r CPBT t}
var.test(desdata$CPBT[desdata$period == "P2"], desdata$CPBT[desdata$period == "P1"])
t.test(x= desdata$CPBT[desdata$period == "P1"], y = desdata$CPBT[desdata$period == "P2"], paired = FALSE, var.equal = TRUE, conf.level = 0.95)
```


```{r IHV descriptive}
desdata$IHV[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$IHV[desdata$period == "P1"])
desdata$IHV[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$IHV[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$IHV[desdata$period == "P2"])
desdata$IHV[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$IHV %>% na.omit() %>% length()
summary(desdata$IHV)
desdata$IHV %>% na.omit() %>% sd()
```
```{r IHV t}
var.test(desdata$IHV[desdata$period == "P2"], desdata$IHV[desdata$period == "P1"])
t.test(x= desdata$IHV[desdata$period == "P1"], y = desdata$IHV[desdata$period == "P2"], paired = FALSE, var.equal = FALSE, conf.level = 0.95)
```



```{r IHV_24}


desdata$IHV_24[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$IHV_24[desdata$period == "P1"])
desdata$IHV_24[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$IHV_24[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$IHV_24[desdata$period == "P2"])
desdata$IHV_24[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$IHV_24 %>% na.omit() %>% length()
summary(desdata$IHV_24)
desdata$IHV_24 %>% na.omit() %>% sd()
```

```{r IHV_24 t}
var.test(desdata$IHV_24[desdata$period == "P2"], desdata$IHV_24[desdata$period == "P1"])
t.test(x= desdata$IHV_24[desdata$period == "P1"], y = desdata$IHV_24[desdata$period == "P2"], paired = FALSE, var.equal = TRUE, conf.level = 0.95)
```


```{r}

library(ggplot2)
theme_set(theme_classic())

hist(desdata$IHV_24, breaks = 12, plot = TRUE, freq = TRUE)

barplot(desdata$IHV_24,desdata$OREhour)
barplot(desdata$IHV_24)

desdata$OREhour <- as.factor(desdata$OREhour)
g <- ggplot(desdata, aes(desdata$OREhour, desdata$IHV_24))
g + geom_boxplot(varwidth=T, fill="steelblue") + 
    labs(title="Box plot", 
         subtitle="Ventilation duration depending on time of arrival in CTICU",
         x="Time of Arrival in CTICU",
         y="Ventilation duration" )

gg <- ggplot(desdata, aes(desdata$period, desdata$IHV_24))
gg + geom_boxplot(varwidth=T, fill="plum") + 
    labs(title="Box plot", 
         subtitle="Ventilation duration depending on time of arrival in CTICU",
         x="Time of Arrival in CTICU",
         y="Ventilation duration" )
```



```{r}

par(mfrow=c(1,1))
hist(desdata$IHV_24[desdata$period == "P1"], main = "Histogram of Ventilation Duration in Day Shift", xlab = "Ventilation Duration for Patients Extubated within 24 hours")
hist(desdata$IHV_24[desdata$period == "P2"], main = "Histogram of Ventilation Duration in Night Shift", xlab = "Ventilation Duration for Patients Extubated within 24 hours")

```
```{r}
g1 <- ggplot(desdata, aes(IHV_24, fill=period))

g1 + geom_histogram()

g1 + geom_histogram(position = ,
                   binwidth = 2, 
                   col="black", 
                   size=.1) +  # change binwidth
  labs(title="Histogram with Auto Binning", 
       subtitle="Engine Displacement across Vehicle Classes")  
```
```{r}
data <- desdata %>% na.omit(IHV_24) %>% group_by()
library(scales)
 ggplot(data, aes(IHV_24)) + 
          geom_bar(aes(y = ..prop.., fill = factor(..x..)), stat="count") + 
          scale_y_continuous(labels=scales::percent) +
          ylab("relative frequencies") +
          facet_grid(~period)
         
```

```{r logistic regression}

 
  
glmdata$period <- as.factor(glmdata$period) %>% relevel(glmdata$period, ref = "P1")
simple_logistic_fit <- glm(formula= period ~ IHV_24, family = binomial(link = "logit"), 
    data = glmdata)
summary(simple_logistic_fit)
```
#Backward selection
##Full model
```{r backward selection}
full_logistic_fit <- glm(formula= period ~ IHV_24+ age+Ethnicity +BMI +PMM +PRM + PPV+ Reop+Urgent +Sug_Dur +Pri_MI +smoker+lung+ PFT +RFD + PAD+ POBPT+ TBU+ XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(full_logistic_fit)

```

```{r remove age }
back_logistic_fit_1 <- glm(formula= period ~ IHV_24+Ethnicity +BMI +PMM +PRM + PPV+ Reop+Urgent +Sug_Dur +Pri_MI +smoker+lung+ PFT +RFD + PAD+ POBPT+ TBU+ XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_1)
```

```{r remove BMI }
back_logistic_fit_2 <- glm(formula= period ~ IHV_24+Ethnicity +PMM +PRM + PPV+ Reop+Urgent +Sug_Dur +Pri_MI +smoker+lung+ PFT +RFD + PAD+ POBPT+ TBU+ XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_2)
```

```{r remove PRM }
back_logistic_fit_3 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV+ Reop+Urgent +Sug_Dur +Pri_MI +smoker+lung+ PFT +RFD + PAD+ POBPT+ TBU+ XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_3)
```


```{r remove Reop }
back_logistic_fit_4 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV+Urgent +Sug_Dur +Pri_MI +smoker+lung+ PFT +RFD + PAD+ POBPT+ TBU+ XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_4)
```

```{r remove Urgent }
back_logistic_fit_5 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV +Sug_Dur +Pri_MI +smoker+lung+ PFT +RFD + PAD+ POBPT+ TBU+ XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_5)
```


```{r remove TBU }
back_logistic_fit_6 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV +Sug_Dur +Pri_MI +smoker+lung+ PFT +RFD + PAD+ POBPT+ XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_6)
```
```{r remove smoker }
back_logistic_fit_7 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV +Sug_Dur +Pri_MI +lung+ PFT +RFD + PAD+ POBPT+ XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_7)
```
```{r remove RFD }
back_logistic_fit_8 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV +Sug_Dur +Pri_MI +smoker+lung+ PFT  + PAD+ POBPT+ XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_8)
```
```{r remove POBPT }
back_logistic_fit_9 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV +Sug_Dur +Pri_MI +smoker+lung+ PFT  + PAD+ XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_9)
```
```{r remove PAD }
back_logistic_fit_10 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV +Sug_Dur +Pri_MI +smoker+lung+ PFT + XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_10)
```

```{r remove Pri_MI }
back_logistic_fit_11 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV +Sug_Dur +smoker+lung+ PFT + XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_11)
```
```{r remove lung }
back_logistic_fit_12 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV +Sug_Dur +smoker+ PFT + XCT+ CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_12)
```
```{r remove XCT }
back_logistic_fit_12 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV +Sug_Dur +smoker+ PFT + CPBT, family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_12)
```
```{r remove CPBT }
back_logistic_fit_13 <- glm(formula= period ~ IHV_24+Ethnicity +PMM + PPV +Sug_Dur +smoker+ PFT , family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_13)
```
```{r remove PPV }
back_logistic_fit_13 <- glm(formula= period ~ IHV_24+Ethnicity +PMM  +Sug_Dur +smoker+ PFT , family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_13)
```
```{r remove PMM }
back_logistic_fit_13 <- glm(formula= period ~ IHV_24+Ethnicity   +Sug_Dur +smoker+ PFT , family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_13)
```

```{r remove Sug_dur }
back_logistic_fit_13 <- glm(formula= period ~ IHV_24+Ethnicity +smoker+ PFT , family = binomial(link = "logit"), data = glmdata)
summary(back_logistic_fit_13)
```

```{r}
exp(5*0.02054 )
```

#Secondary outcome des
```{r Hos_LOS descriptive}
desdata$Hos_LOS[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$Hos_LOS[desdata$period == "P1"])
desdata$Hos_LOS[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$Hos_LOS[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$Hos_LOS[desdata$period == "P2"])
desdata$Hos_LOS[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$Hos_LOS %>% na.omit() %>% length()
summary(desdata$Hos_LOS)
desdata$Hos_LOS %>% na.omit() %>% sd()
```

```{r Hos_LOS t}
var.test(desdata$Hos_LOS[desdata$period == "P2"], desdata$Hos_LOS[desdata$period == "P1"])
t.test(x= desdata$Hos_LOS[desdata$period == "P1"], y = desdata$Hos_LOS[desdata$period == "P2"], paired = FALSE, var.equal = FALSE, conf.level = 0.95)
```

```{r ICU_LOS descriptive}
desdata$ICU_LOS[desdata$period == "P1"] %>% na.omit() %>% length()
summary(desdata$ICU_LOS[desdata$period == "P1"])
desdata$ICU_LOS[desdata$period == "P1"] %>% na.omit() %>% sd()
desdata$ICU_LOS[desdata$period == "P2"] %>% na.omit() %>% length()
summary(desdata$ICU_LOS[desdata$period == "P2"])
desdata$ICU_LOS[desdata$period == "P2"] %>% na.omit() %>% sd()
desdata$ICU_LOS %>% na.omit() %>% length()
summary(desdata$ICU_LOS)
desdata$ICU_LOS %>% na.omit() %>% sd()
```

```{r ICU_LOS t}
var.test(desdata$ICU_LOS[desdata$period == "P2"], desdata$ICU_LOS[desdata$period == "P1"])
t.test(x= desdata$ICU_LOS[desdata$period == "P1"], y = desdata$ICU_LOS[desdata$period == "P2"], paired = FALSE, var.equal = FALSE, conf.level = 0.95)
```
```{r ICU_LOS logistic}
logistic_fit_ICU_LOS <- glm(formula= period ~ ICU_LOS+Ethnicity +smoker+ PFT , family = binomial(link = "logit"), data = glmdata)
summary(logistic_fit_ICU_LOS)
```

```{r Reintub descriptive}

#glmdata$Reintub[desdata$Reintub == "Unknown"] <- NA

length(glmdata$Reintub)
sum(is.na(glmdata$Reintub))
sum(is.na(glmdata$Reintub)) / length(glmdata$Reintub)
table(glmdata$Reintub)

#table(glmdata$Reintub) / length(glmdata$Reintub)
paste(round(100*(table(glmdata$Reintub) / 861), 2), "%", sep="")

length(glmdata$Reintub[glmdata$period == "P1"])
length(glmdata$Reintub[glmdata$period == "P2"])

sum(is.na(glmdata$Reintub[glmdata$period == "P1"]))
sum(is.na(glmdata$Reintub[glmdata$period == "P2"]))

table(glmdata$Reintub[glmdata$period == "P1"]) 
table(glmdata$Reintub[glmdata$period == "P2"]) 

#table(glmdata$Reintub[glmdata$period == "P1"]) / length(glmdata$Reintub[glmdata$period == "P1"])
paste(round(100*(table(glmdata$Reintub[glmdata$period == "P1"]) / length(glmdata$Reintub[glmdata$period == "P1"])), 2), "%", sep="")

#table(glmdata$Reintub[glmdata$period == "P2"]) / length(glmdata$Reintub[glmdata$period == "P2"])
paste(round(100*(table(glmdata$Reintub[glmdata$period == "P2"]) / length(glmdata$Reintub[glmdata$period == "P2"])), 2), "%", sep="")

chisq.test(glmdata$Reintub,glmdata$period, correct = FALSE)
```

```{r Re_ICU  descriptive}

#glmdata$Re_ICU [desdata$Re_ICU  != "No" | desdata$Re_ICU !="Unknown"] <- "Yes"
#glmdata$Re_ICU [desdata$Re_ICU  == "No"] <- "No"
#glmdata$Re_ICU [desdata$Re_ICU  == "Unknown"] <- NA


length(glmdata$Re_ICU )
sum(is.na(glmdata$Re_ICU ))
sum(is.na(glmdata$Re_ICU )) / length(glmdata$Re_ICU )
table(glmdata$Re_ICU )

#table(glmdata$Re_ICU ) / length(glmdata$Re_ICU )
paste(round(100*(table(glmdata$Re_ICU ) / (length(na.omit(glmdata$Re_ICU )))), 2), "%", sep="")

length(na.omit(glmdata$Re_ICU [glmdata$period == "P1"]))
length(na.omit(glmdata$Re_ICU [glmdata$period == "P2"]))

sum(is.na(glmdata$Re_ICU [glmdata$period == "P1"]))
sum(is.na(glmdata$Re_ICU [glmdata$period == "P2"]))

table(glmdata$Re_ICU [glmdata$period == "P1"]) 
table(glmdata$Re_ICU [glmdata$period == "P2"]) 

#table(glmdata$Re_ICU [glmdata$period == "P1"]) / length(glmdata$Re_ICU [glmdata$period == "P1"])
paste(round(100*(table(glmdata$Re_ICU [glmdata$period == "P1"]) / length(na.omit(glmdata$Re_ICU [glmdata$period == "P1"]))), 2), "%", sep="")

#table(glmdata$Re_ICU [glmdata$period == "P2"]) / length(glmdata$Re_ICU [glmdata$period == "P2"])
paste(round(100*(table(glmdata$Re_ICU [glmdata$period == "P2"]) / length(na.omit(glmdata$Re_ICU [glmdata$period == "P2"]))), 2), "%", sep="")

chisq.test(glmdata$Re_ICU ,glmdata$period, correct = FALSE)
```

```{r Mor_disc  descriptive}


glmdata$Mor_disc [desdata$Mor_disc  == "Dead"] <- "Dead"
glmdata$Mor_disc [desdata$Mor_disc  != "Dead"] <- "Alive"


length(glmdata$Mor_disc )
sum(is.na(glmdata$Mor_disc ))
sum(is.na(glmdata$Mor_disc )) / length(glmdata$Mor_disc )
table(glmdata$Mor_disc )

#table(glmdata$Mor_disc ) / length(glmdata$Mor_disc )
paste(round(100*(table(glmdata$Mor_disc ) / (length(na.omit(glmdata$Mor_disc )))), 2), "%", sep="")

length(na.omit(glmdata$Mor_disc [glmdata$period == "P1"]))
length(na.omit(glmdata$Mor_disc [glmdata$period == "P2"]))

sum(is.na(glmdata$Mor_disc [glmdata$period == "P1"]))
sum(is.na(glmdata$Mor_disc [glmdata$period == "P2"]))

table(glmdata$Mor_disc [glmdata$period == "P1"]) 
table(glmdata$Mor_disc [glmdata$period == "P2"]) 

#table(glmdata$Mor_disc [glmdata$period == "P1"]) / length(glmdata$Mor_disc [glmdata$period == "P1"])
paste(round(100*(table(glmdata$Mor_disc [glmdata$period == "P1"]) / length(na.omit(glmdata$Mor_disc [glmdata$period == "P1"]))), 2), "%", sep="")

#table(glmdata$Mor_disc [glmdata$period == "P2"]) / length(glmdata$Mor_disc [glmdata$period == "P2"])
paste(round(100*(table(glmdata$Mor_disc [glmdata$period == "P2"]) / length(na.omit(glmdata$Mor_disc [glmdata$period == "P2"]))), 2), "%", sep="")

fisher.test(glmdata$Mor_disc ,glmdata$period)
```


#```{r}
Reintub,
Post_pneu, 
Post_throm ,
Post_stroke ,
Re_ICU , 
Hos_LOS, 
ICU_LOS, 
Mor_disc,
#```

